tag-template: 'apmt-$RESOLVED_VERSION'
template: |
  ## What’s Changed

  $CHANGES
  
  All contributors: $CONTRIBUTORS
  
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'documentation'
      - 'other'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor
exclude-labels:
  - 'skip-changelog'
