template: |
  ## What’s Changed

  $CHANGES
  
  All contributors: $CONTRIBUTORS
  
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'maintenance'
      - 'documentation'
      - 'other'
exclude-labels:
  - 'skip-changelog'
