name: Release new version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort     
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  release:
    runs-on: ubuntu-latest
    name: Release version
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get version
        run: echo "Releasing version ${{ github.event.release.tag_name }}"
      - name: Verify release
        run: ./gradlew verifyRelease
      - name: Publish version
        run: ./gradlew publish
        
