name: Release new version

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort     
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  release:
    runs-on: ubuntu-latest
    name: Release version
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Get version
        run: echo "Releasing version ${{ github.event.release.tag_name }}"
      - name: Verify release
        run: ./gradlew verifyRelease -Prelease.disableRemoteCheck
      - name: Configure Maven
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          cd ~ && mkdir .m2
          cat <<EOF> ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>ossrh</id>
                <username>${OSSRH_USERNAME}</username>
                <password>${OSSRH_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF
          
      - name: Publish version
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword:  ${{ secrets.GPG_SIGNING_PASSPHRASE }}
        run: ./gradlew publish
        
